//Testfile for all CRUD operations

POST https://school-restaurant-api.azurewebsites.net/restaurant/create
Content-Type: application/json

{
    "name": "La Trattoria",
    "address": {
        "street": "Via Roma 23",
        "zip": "00100",
        "city": "Rome"
    }
}


### Create a new customer. Id generates by mongoDb
POST https://school-restaurant-api.azurewebsites.net/customer/create
Content-Type: application/json

{
  "name": "aaFranzén4",
  "lastname": "Sebastian4",
  "email": "someone@somedomain.com",
  "phone": "070-1112233"
}

### Get customer with ID "64f765086436ceddb351a77d"
GET https://school-restaurant-api.azurewebsites.net/customer/64f765086436ceddb351a77d

### Update customer with ID "623b85d54396b96c57bde7c3"
PUT https://school-restaurant-api.azurewebsites.net/customer/update/623b85d54396b96c57bde7c3
Content-Type: application/json

{
  "id": "623b85d54396b96c57bde7c3",
  "name": "UpdatedName",
  "lastname": "UpdatedLastName",
  "email": "updatedemail@somedomain.com",
  "phone": "070-2223344"
}

###

GET https://school-restaurant-api.azurewebsites.net/restaurant/64f7598c264e4838c0d69dd5

###

// Test for fetching bookings by id
GET https://school-restaurant-api.azurewebsites.net/booking/623b85d54396b96c57bde7c3

###

// Test for fetching bookings for a specific restaurant ID
GET https://school-restaurant-api.azurewebsites.net/booking/restaurant/64f862916436ceddb351c43e


###

// Test for creating a booking
POST https://school-restaurant-api.azurewebsites.net/booking/create
Content-Type: application/json

{
    "restaurantId": "64f862916436ceddb351c43e",
    "date": "2026-07-02",
    "time": "21:00",
    "numberOfGuests": 5,
    "customer": {
        "name": "son",
        "lastname": "Hello",
        "email": "agd43s@somedomain.com",
        "phone": "070-1112234"
    }
}

###

// Test for updating a booking
PUT https://school-restaurant-api.azurewebsites.net/booking/update/623b85d54396b96c57bde7c3
Content-Type: application/json

{
    "id": "623b85d54396b96c57bde7c3",
    "restaurantId": "623b85d54396b96c57bde7c3",
    "date": "2022-05-01",
    "time": "21:00",
    "numberOfGuests": 3,
    "customerId": "64f9d9495eecc88857a6a2cc"
}

###

// Test for deleting a booking
DELETE https://school-restaurant-api.azurewebsites.net/booking/delete/64f9e2bb5eecc88857a6a2e1



